# Generated by Django 4.2.23 on 2025-06-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoahorro',
            old_name='embbeding',
            new_name='vector_embedding',
        ),
        migrations.AddField(
            model_name='productoahorro',
            name='institucion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productoahorro',
            name='moneda',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productoahorro',
            name='saldo_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productoahorro',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productoahorro',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
