# Generated by Django 4.2.23 on 2025-06-16 16:59

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_embbeding_productoahorro_vector_embedding_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoahorro',
            old_name='nombre',
            new_name='nombre_entidad_financiera',
        ),
        migrations.RemoveField(
            model_name='productoahorro',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='productoahorro',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='productoahorro',
            name='saldo_minimo',
        ),
        migrations.RemoveField(
            model_name='productoahorro',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='productoahorro',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='productoahorro',
            name='region',
            field=models.CharField(choices=[('AM', 'Amazonas'), ('AN', 'Ancash'), ('AP', 'Apurímac'), ('AR', 'Arequipa'), ('AY', 'Ayacucho'), ('CA', 'Cajamarca'), ('CU', 'Cusco'), ('HU', 'Huancavelica'), ('HV', 'Huánuco'), ('IC', 'Ica'), ('JU', 'Junín'), ('LA', 'La Libertad'), ('LI', 'Lima'), ('LO', 'Loreto'), ('MD', 'Madre de Dios'), ('MO', 'Moquegua'), ('PA', 'Pasco'), ('PI', 'Piura'), ('PU', 'Puno'), ('SM', 'San Martín'), ('TA', 'Tacna'), ('TU', 'Tumbes'), ('UC', 'Ucayali'), ('LI', 'Lima Provincia')], default='LI', max_length=2),
        ),
        migrations.AddField(
            model_name='productoahorro',
            name='tasa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tasa en porcentaje, ejemplo 3.50', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productoahorro',
            name='tipo_cuenta',
            field=models.CharField(choices=[('CTS', 'CTS'), ('SUELDO', 'Sueldo'), ('AHORRO', 'Ahorro')], default='AHORRO', max_length=10),
        ),
        migrations.AddField(
            model_name='productoahorro',
            name='tipo_institucion',
            field=models.CharField(choices=[('BANCO', 'Banco'), ('CAJA', 'Caja'), ('FINANCIERA', 'Financiera')], default='BANCO', max_length=15),
        ),
        migrations.AlterField(
            model_name='productoahorro',
            name='moneda',
            field=models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='productoahorro',
            name='vector_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
