# Generated by Django 4.2.23 on 2025-06-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_nombre_productoahorro_nombre_entidad_financiera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoahorro',
            name='moneda',
            field=models.CharField(choices=[('soles', 'Soles'), ('dolares', 'Dólares')], default='soles', max_length=10),
        ),
        migrations.AlterField(
            model_name='productoahorro',
            name='region',
            field=models.CharField(choices=[('amazonas', 'Amazonas'), ('ancash', 'Ancash'), ('apurimas', 'Apurímac'), ('arequipa', 'Arequipa'), ('ayacucho', 'Ayacucho'), ('cajamarca', 'Cajamarca'), ('cusco', 'Cusco'), ('huancavelica', 'Huancavelica'), ('huanuco', 'Huánuco'), ('ica', 'Ica'), ('junin', 'Junín'), ('la libertad', 'La Libertad'), ('lima', 'Lima'), ('loreto', 'Loreto'), ('madre de dios', 'Madre de Dios'), ('moquegua', 'Moquegua'), ('pasco', 'Pasco'), ('piura', 'Piura'), ('puno', 'Puno'), ('san martin', 'San Martín'), ('tacna', 'Tacna'), ('tumbes', 'Tumbes'), ('ucayali', 'Ucayali'), ('lima provincia', 'Lima Provincia')], default='lima', max_length=20),
        ),
        migrations.AlterField(
            model_name='productoahorro',
            name='tipo_cuenta',
            field=models.CharField(choices=[('CTS', 'CTS'), ('sueldo', 'Sueldo'), ('ahorro', 'Ahorro')], default='ahorro', max_length=10),
        ),
        migrations.AlterField(
            model_name='productoahorro',
            name='tipo_institucion',
            field=models.CharField(choices=[('banco', 'Banco'), ('caja', 'Caja'), ('financiera', 'Financiera')], default='banco', max_length=15),
        ),
    ]
