# Generated by Django 4.2.23 on 2025-06-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_productoahorro_moneda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoahorro',
            name='saldo_promedio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
