# Generated by Django 4.2.23 on 2025-07-18 21:11

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_productoahorro_saldo_promedio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAhorroSBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('entidad', models.CharField(max_length=200)),
                ('tasa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('tipo_cuenta', models.CharField(max_length=100)),
                ('condiciones', models.CharField(max_length=200)),
                ('moneda', models.CharField(max_length=100)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
            ],
        ),
    ]
